window.YSD_DATA = {
  "meta": {
    "title": "云上党 · 古树名木数字地图与数据大屏",
    "source": "上党区古树名木.xlsx",
    "center": [
      113.04,
      36.05
    ],
    "zoom": 11
  },
  "kpis": {
    "total": 53,
    "withCoord": 53,
    "maxAge": 2111,
    "avgAge": 552.8,
    "gradeOne": 22,
    "speciesCount": 8,
    "townCount": 9
  },
  "oldest": {
    "id": "14040400016",
    "category": "古树",
    "province": "山西省",
    "city": "长治市",
    "district": "上党区",
    "town": "苏店镇",
    "village": "原村村委会",
    "place": "付文喜院北",
    "family": "豆科",
    "genus": "槐属",
    "species": "国槐",
    "scientificName": "Sophora japonica L.",
    "commonName": "",
    "growthPlace": "乡村",
    "distribution": "散生",
    "lng": 113.151111,
    "lat": 36.078333,
    "ownership": "集体",
    "age": 2111,
    "grade": "1",
    "height": 20.8,
    "chest": 690,
    "ground": null,
    "avgCrown": 21.5,
    "ewCrown": 20,
    "nsCrown": 23,
    "altitude": 1040,
    "soil": "未标注",
    "growth": "衰弱",
    "environment": "好",
    "damage": "暂无明显损伤记录",
    "story": "已记录保护措施：护栏,树池",
    "maintainerType": "未标注",
    "maintainer": "村委",
    "department": "未标注",
    "measure": "护栏,树池",
    "revive": "待补充",
    "surveyPerson": "王思远",
    "surveyDate": "2017-07-28",
    "archiveYear": "未标注",
    "name": "苏店镇·原村村委会·付文喜院北 国槐",
    "address": "山西省长治市上党区苏店镇原村村委会付文喜院北",
    "location": "付文喜院北",
    "protection": "护栏,树池",
    "coordinate_status": "正常",
    "data_note": ""
  },
  "towns": [
    {
      "name": "荫城镇",
      "value": 24
    },
    {
      "name": "郝家庄镇",
      "value": 7
    },
    {
      "name": "苏店镇",
      "value": 5
    },
    {
      "name": "西火镇",
      "value": 5
    },
    {
      "name": "八义镇",
      "value": 4
    },
    {
      "name": "南宋镇",
      "value": 3
    },
    {
      "name": "韩店街道",
      "value": 2
    },
    {
      "name": "振兴新区",
      "value": 2
    },
    {
      "name": "北呈乡",
      "value": 1
    }
  ],
  "species": [
    {
      "name": "国槐",
      "value": 34
    },
    {
      "name": "侧柏",
      "value": 8
    },
    {
      "name": "油松",
      "value": 4
    },
    {
      "name": "榆树",
      "value": 3
    },
    {
      "name": "核桃",
      "value": 1
    },
    {
      "name": "君迁子",
      "value": 1
    },
    {
      "name": "山合欢",
      "value": 1
    },
    {
      "name": "皂荚",
      "value": 1
    }
  ],
  "grades": [
    {
      "name": "3",
      "value": 24
    },
    {
      "name": "1",
      "value": 22
    },
    {
      "name": "2",
      "value": 7
    }
  ],
  "growth": [
    {
      "name": "正常",
      "value": 26
    },
    {
      "name": "衰弱",
      "value": 20
    },
    {
      "name": "濒危",
      "value": 7
    }
  ],
  "environment": [
    {
      "name": "好",
      "value": 28
    },
    {
      "name": "差",
      "value": 25
    }
  ],
  "ownership": [
    {
      "name": "集体",
      "value": 39
    },
    {
      "name": "个人",
      "value": 14
    }
  ],
  "families": [
    {
      "name": "豆科",
      "value": 36
    },
    {
      "name": "柏科",
      "value": 8
    },
    {
      "name": "松科",
      "value": 4
    },
    {
      "name": "榆科",
      "value": 3
    },
    {
      "name": "胡桃科",
      "value": 1
    },
    {
      "name": "柿科",
      "value": 1
    }
  ],
  "points": [
    {
      "id": "14040400001",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "韩店街道",
      "village": "韩店村委会",
      "place": "王家圪倒",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "城区",
      "distribution": "散生",
      "lng": 113.0441667,
      "lat": 36.0458333,
      "ownership": "个人",
      "age": 1484,
      "grade": "1",
      "height": 18.4,
      "chest": 440,
      "ground": null,
      "avgCrown": 18,
      "ewCrown": 20,
      "nsCrown": 16,
      "altitude": 980,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "二十多年前，有个小女孩经过古树准备回家时，听到背后有人喊她的名字，转身向后寻找，就这转身的功夫，女孩前面的房屋轰然倒塌。村民认为这是古树有灵性，喊住小女孩救了她一命。",
      "maintainerType": "未标注",
      "maintainer": "王文生",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-22",
      "archiveYear": "未标注",
      "name": "韩店街道·韩店村委会·王家圪倒 国槐",
      "address": "山西省长治市上党区韩店街道韩店村委会王家圪倒",
      "location": "王家圪倒",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400002",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "韩店街道",
      "village": "光明北路社区委员会",
      "place": "随高生院东西墙外",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "城区",
      "distribution": "散生",
      "lng": 113.022778,
      "lat": 36.069444,
      "ownership": "集体",
      "age": 1822,
      "grade": "1",
      "height": 9.3,
      "chest": 590,
      "ground": null,
      "avgCrown": 14.5,
      "ewCrown": 13,
      "nsCrown": 16,
      "altitude": 980,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树洞封堵",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树洞封堵",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-22",
      "archiveYear": "未标注",
      "name": "韩店街道·光明北路社区委员会·随高生院东西墙外 国槐",
      "address": "山西省长治市上党区韩店街道光明北路社区委员会随高生院东西墙外",
      "location": "随高生院东西墙外",
      "protection": "护栏,树洞封堵",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400003",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "北呈乡",
      "village": "北呈村委会",
      "place": "后街小庙",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113,
      "lat": 36.076667,
      "ownership": "集体",
      "age": 1462,
      "grade": "1",
      "height": 7.5,
      "chest": 305,
      "ground": null,
      "avgCrown": 10,
      "ewCrown": 10,
      "nsCrown": 10,
      "altitude": 950,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "主干被烧，现存树干为原主干四分之一，向南侧倾斜40度",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "树洞封堵",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-22",
      "archiveYear": "未标注",
      "name": "北呈乡·北呈村委会·后街小庙 国槐",
      "address": "山西省长治市上党区北呈乡北呈村委会后街小庙",
      "location": "后街小庙",
      "protection": "树洞封堵",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400004",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "景家沟村委会",
      "place": "大庙西墙下",
      "family": "榆科",
      "genus": "榆属",
      "species": "榆树",
      "scientificName": "Ulmus pumila L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.004444,
      "lat": 36.11,
      "ownership": "集体",
      "age": 350,
      "grade": "2",
      "height": 17.9,
      "chest": 290,
      "ground": null,
      "avgCrown": 16.5,
      "ewCrown": 16,
      "nsCrown": 17,
      "altitude": 0,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "80岁以上老人都说从记事起就有此树",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-23",
      "archiveYear": "未标注",
      "name": "郝家庄镇·景家沟村委会·大庙西墙下 榆树",
      "address": "山西省长治市上党区郝家庄镇景家沟村委会大庙西墙下",
      "location": "大庙西墙下",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400005",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "郝家庄村委会",
      "place": "女娲庙天台山",
      "family": "豆科",
      "genus": "皂荚属",
      "species": "皂荚",
      "scientificName": "Gleditsia sinensis Lam.",
      "commonName": "",
      "growthPlace": "城区",
      "distribution": "散生",
      "lng": 113.024167,
      "lat": 36.134167,
      "ownership": "集体",
      "age": 600,
      "grade": "1",
      "height": 13.2,
      "chest": 390,
      "ground": null,
      "avgCrown": 15.5,
      "ewCrown": 14,
      "nsCrown": 17,
      "altitude": 940,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-23",
      "archiveYear": "未标注",
      "name": "郝家庄镇·郝家庄村委会·女娲庙天台山 皂荚",
      "address": "山西省长治市上党区郝家庄镇郝家庄村委会女娲庙天台山",
      "location": "女娲庙天台山",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400006",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "郝家庄村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.009167,
      "lat": 36.113056,
      "ownership": "集体",
      "age": 450,
      "grade": "2",
      "height": 10.3,
      "chest": 330,
      "ground": null,
      "avgCrown": 16.5,
      "ewCrown": 15,
      "nsCrown": 18,
      "altitude": 930,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "主干缺损，现存树木为萌生",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-23",
      "archiveYear": "未标注",
      "name": "郝家庄镇·郝家庄村委会 国槐",
      "address": "山西省长治市上党区郝家庄镇郝家庄村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400007",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "上郝村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.009444,
      "lat": 36.133056,
      "ownership": "集体",
      "age": 400,
      "grade": "2",
      "height": 10.1,
      "chest": 300,
      "ground": null,
      "avgCrown": 8.5,
      "ewCrown": 6,
      "nsCrown": 11,
      "altitude": 940,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "树冠缺损五分之四，2016年开始枯死加速",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-23",
      "archiveYear": "未标注",
      "name": "郝家庄镇·上郝村委会 国槐",
      "address": "山西省长治市上党区郝家庄镇上郝村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400008",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "上郝村委会",
      "place": "未标注",
      "family": "胡桃科",
      "genus": "胡桃属",
      "species": "核桃",
      "scientificName": "Juglans regia",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.010556,
      "lat": 36.133611,
      "ownership": "个人",
      "age": 150,
      "grade": "3",
      "height": 12.4,
      "chest": 230,
      "ground": null,
      "avgCrown": 17,
      "ewCrown": 18,
      "nsCrown": 16,
      "altitude": 950,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "树木权属为牛枝兵",
      "maintainerType": "未标注",
      "maintainer": "申福香",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-23",
      "archiveYear": "未标注",
      "name": "郝家庄镇·上郝村委会 核桃",
      "address": "山西省长治市上党区郝家庄镇上郝村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400010",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "南宋镇",
      "village": "西沟村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.088889,
      "lat": 35.929167,
      "ownership": "集体",
      "age": 500,
      "grade": "1",
      "height": 9.8,
      "chest": 360,
      "ground": null,
      "avgCrown": 12,
      "ewCrown": 13,
      "nsCrown": 11,
      "altitude": 1130,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "树干中空",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-28",
      "archiveYear": "未标注",
      "name": "南宋镇·西沟村委会 国槐",
      "address": "山西省长治市上党区南宋镇西沟村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400011",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "南宋镇",
      "village": "南苍和村委会",
      "place": "未标注",
      "family": "松科",
      "genus": "松属",
      "species": "油松",
      "scientificName": "Pinus tabuliformis Carriere",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.002222,
      "lat": 35.9325,
      "ownership": "集体",
      "age": 200,
      "grade": "3",
      "height": 8.4,
      "chest": 180,
      "ground": null,
      "avgCrown": 9,
      "ewCrown": 11,
      "nsCrown": 7,
      "altitude": 1060,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-28",
      "archiveYear": "未标注",
      "name": "南宋镇·南苍和村委会 油松",
      "address": "山西省长治市上党区南宋镇南苍和村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400012",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "南宋镇",
      "village": "南苍和村委会",
      "place": "未标注",
      "family": "松科",
      "genus": "松属",
      "species": "油松",
      "scientificName": "Pinus tabuliformis Carriere",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.001944,
      "lat": 35.930556,
      "ownership": "集体",
      "age": 100,
      "grade": "3",
      "height": 3.1,
      "chest": 120,
      "ground": null,
      "avgCrown": 7.5,
      "ewCrown": 9,
      "nsCrown": 6,
      "altitude": 1090,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-06-28",
      "archiveYear": "未标注",
      "name": "南宋镇·南苍和村委会 油松",
      "address": "山西省长治市上党区南宋镇南苍和村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400013",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "苏店镇",
      "village": "东贾村委会",
      "place": "南社贾金锁院西",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.094167,
      "lat": 36.102222,
      "ownership": "集体",
      "age": 750,
      "grade": "1",
      "height": 13.3,
      "chest": 390,
      "ground": null,
      "avgCrown": 16.5,
      "ewCrown": 14,
      "nsCrown": 19,
      "altitude": 950,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树洞封堵",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "树洞封堵",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-17",
      "archiveYear": "未标注",
      "name": "苏店镇·东贾村委会·南社贾金锁院西 国槐",
      "address": "山西省长治市上党区苏店镇东贾村委会南社贾金锁院西",
      "location": "南社贾金锁院西",
      "protection": "树洞封堵",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400014",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "苏店镇",
      "village": "南董村委会",
      "place": "大队南十字小广场",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.084722,
      "lat": 36.091944,
      "ownership": "集体",
      "age": 450,
      "grade": "2",
      "height": 13.8,
      "chest": 310,
      "ground": null,
      "avgCrown": 20,
      "ewCrown": 20,
      "nsCrown": 20,
      "altitude": 980,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-17",
      "archiveYear": "未标注",
      "name": "苏店镇·南董村委会·大队南十字小广场 国槐",
      "address": "山西省长治市上党区苏店镇南董村委会大队南十字小广场",
      "location": "大队南十字小广场",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400015",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "苏店镇",
      "village": "东贾村委会",
      "place": "14队村中路边",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.1425,
      "lat": 36.100833,
      "ownership": "集体",
      "age": 1396,
      "grade": "1",
      "height": 20.9,
      "chest": 450,
      "ground": null,
      "avgCrown": 18,
      "ewCrown": 19,
      "nsCrown": 17,
      "altitude": 1070,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "苏店镇·东贾村委会·14队村中路边 国槐",
      "address": "山西省长治市上党区苏店镇东贾村委会14队村中路边",
      "location": "14队村中路边",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400016",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "苏店镇",
      "village": "原村村委会",
      "place": "付文喜院北",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.151111,
      "lat": 36.078333,
      "ownership": "集体",
      "age": 2111,
      "grade": "1",
      "height": 20.8,
      "chest": 690,
      "ground": null,
      "avgCrown": 21.5,
      "ewCrown": 20,
      "nsCrown": 23,
      "altitude": 1040,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "苏店镇·原村村委会·付文喜院北 国槐",
      "address": "山西省长治市上党区苏店镇原村村委会付文喜院北",
      "location": "付文喜院北",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400017",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "苏店镇",
      "village": "西岭村委会",
      "place": "后山",
      "family": "松科",
      "genus": "松属",
      "species": "油松",
      "scientificName": "Pinus tabuliformis Carriere",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.159722,
      "lat": 36.134167,
      "ownership": "集体",
      "age": 505,
      "grade": "1",
      "height": 16.5,
      "chest": 250,
      "ground": null,
      "avgCrown": 14.5,
      "ewCrown": 14,
      "nsCrown": 15,
      "altitude": 1190,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "苏店镇·西岭村委会·后山 油松",
      "address": "山西省长治市上党区苏店镇西岭村委会后山",
      "location": "后山",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400018",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "八义镇",
      "village": "师庄村委会",
      "place": "韩金胜院门前",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 112.986667,
      "lat": 35.946667,
      "ownership": "集体",
      "age": 1500,
      "grade": "1",
      "height": 22.7,
      "chest": 480,
      "ground": null,
      "avgCrown": 18,
      "ewCrown": 18,
      "nsCrown": 18,
      "altitude": 1070,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "八义镇·师庄村委会·韩金胜院门前 国槐",
      "address": "山西省长治市上党区八义镇师庄村委会韩金胜院门前",
      "location": "韩金胜院门前",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400019",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "八义镇",
      "village": "八义村委会",
      "place": "东头赵红卫院西",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.022778,
      "lat": 35.966389,
      "ownership": "集体",
      "age": 1675,
      "grade": "1",
      "height": 13.5,
      "chest": 550,
      "ground": null,
      "avgCrown": 13,
      "ewCrown": 13,
      "nsCrown": 13,
      "altitude": 1000,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "八义镇·八义村委会·东头赵红卫院西 国槐",
      "address": "山西省长治市上党区八义镇八义村委会东头赵红卫院西",
      "location": "东头赵红卫院西",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400020",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "八义镇",
      "village": "八义村委会",
      "place": "河西张玉珍院门口",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.0141677,
      "lat": 35.966944,
      "ownership": "集体",
      "age": 1485,
      "grade": "1",
      "height": 16.8,
      "chest": 470,
      "ground": null,
      "avgCrown": 10.5,
      "ewCrown": 11,
      "nsCrown": 10,
      "altitude": 990,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "八义镇·八义村委会·河西张玉珍院门口 国槐",
      "address": "山西省长治市上党区八义镇八义村委会河西张玉珍院门口",
      "location": "河西张玉珍院门口",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400021",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "八义镇",
      "village": "常蒋村委会",
      "place": "崔新气院南",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.045278,
      "lat": 35.988889,
      "ownership": "集体",
      "age": 1500,
      "grade": "1",
      "height": 13.5,
      "chest": 490,
      "ground": null,
      "avgCrown": 13,
      "ewCrown": 14,
      "nsCrown": 12,
      "altitude": 1000,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "树冠大部分缺失",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-07-28",
      "archiveYear": "未标注",
      "name": "八义镇·常蒋村委会·崔新气院南 国槐",
      "address": "山西省长治市上党区八义镇常蒋村委会崔新气院南",
      "location": "崔新气院南",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400022",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "荫城村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.1108333,
      "lat": 35.952222,
      "ownership": "集体",
      "age": 570,
      "grade": "1",
      "height": 10.5,
      "chest": 350,
      "ground": null,
      "avgCrown": 8,
      "ewCrown": 7,
      "nsCrown": 9,
      "altitude": 1040,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·荫城村委会 国槐",
      "address": "山西省长治市上党区荫城镇荫城村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400023",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "荫城村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.115556,
      "lat": 35.958056,
      "ownership": "集体",
      "age": 600,
      "grade": "1",
      "height": 10.5,
      "chest": 380,
      "ground": null,
      "avgCrown": 9,
      "ewCrown": 8,
      "nsCrown": 10,
      "altitude": 1030,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "树冠大部分缺失",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·荫城村委会 国槐",
      "address": "山西省长治市上党区荫城镇荫城村委会未标注",
      "location": "未标注",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400024",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "荫城村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.110556,
      "lat": 35.954722,
      "ownership": "集体",
      "age": 660,
      "grade": "1",
      "height": 12.2,
      "chest": 440,
      "ground": null,
      "avgCrown": 15,
      "ewCrown": 16,
      "nsCrown": 14,
      "altitude": 1010,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "槐抱椿",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·荫城村委会 国槐",
      "address": "山西省长治市上党区荫城镇荫城村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400025",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "桑梓二村村委会",
      "place": "圣人观",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.094722,
      "lat": 35.962778,
      "ownership": "集体",
      "age": 200,
      "grade": "3",
      "height": 16.5,
      "chest": 125,
      "ground": null,
      "avgCrown": 6.5,
      "ewCrown": 5,
      "nsCrown": 8,
      "altitude": 1000,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·桑梓二村村委会·圣人观 侧柏",
      "address": "山西省长治市上党区荫城镇桑梓二村村委会圣人观",
      "location": "圣人观",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400026",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "桑梓二村村委会",
      "place": "圣人观",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.094722,
      "lat": 35.962778,
      "ownership": "集体",
      "age": 115,
      "grade": "3",
      "height": 16,
      "chest": 99,
      "ground": null,
      "avgCrown": 5.5,
      "ewCrown": 6,
      "nsCrown": 5,
      "altitude": 1000,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·桑梓二村村委会·圣人观 侧柏",
      "address": "山西省长治市上党区荫城镇桑梓二村村委会圣人观",
      "location": "圣人观",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400027",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "北峪村委会",
      "place": "石岸上",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.126944,
      "lat": 35.978056,
      "ownership": "集体",
      "age": 233,
      "grade": "3",
      "height": 12.5,
      "chest": 250,
      "ground": null,
      "avgCrown": 12.5,
      "ewCrown": 13,
      "nsCrown": 12,
      "altitude": 1050,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·北峪村委会·石岸上 国槐",
      "address": "山西省长治市上党区荫城镇北峪村委会石岸上",
      "location": "石岸上",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400028",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "北峪村委会",
      "place": "西坡崖",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.124167,
      "lat": 35.977222,
      "ownership": "集体",
      "age": 233,
      "grade": "3",
      "height": 14,
      "chest": 250,
      "ground": null,
      "avgCrown": 14.5,
      "ewCrown": 15,
      "nsCrown": 14,
      "altitude": 1050,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·北峪村委会·西坡崖 国槐",
      "address": "山西省长治市上党区荫城镇北峪村委会西坡崖",
      "location": "西坡崖",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400029",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "琚贵则院内",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.136219,
      "lat": 35.965106,
      "ownership": "个人",
      "age": 133,
      "grade": "3",
      "height": 14,
      "chest": 110,
      "ground": null,
      "avgCrown": 4.5,
      "ewCrown": 4,
      "nsCrown": 5,
      "altitude": 1050,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树池",
      "maintainerType": "未标注",
      "maintainer": "琚贵则",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·琚贵则院内 侧柏",
      "address": "山西省长治市上党区荫城镇横河村委会琚贵则院内",
      "location": "琚贵则院内",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400030",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "赵家圪道",
      "family": "榆科",
      "genus": "榆属",
      "species": "榆树",
      "scientificName": "Ulmus pumila L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.148333,
      "lat": 35.961667,
      "ownership": "个人",
      "age": 159,
      "grade": "3",
      "height": 22,
      "chest": 190,
      "ground": null,
      "avgCrown": 11,
      "ewCrown": 12,
      "nsCrown": 10,
      "altitude": 1100,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "石会义",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·赵家圪道 榆树",
      "address": "山西省长治市上党区荫城镇横河村委会赵家圪道",
      "location": "赵家圪道",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400031",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "赵家圪道",
      "family": "榆科",
      "genus": "榆属",
      "species": "榆树",
      "scientificName": "Ulmus pumila L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.148611,
      "lat": 35.961944,
      "ownership": "个人",
      "age": 147,
      "grade": "3",
      "height": 13,
      "chest": 185,
      "ground": null,
      "avgCrown": 12.5,
      "ewCrown": 10,
      "nsCrown": 15,
      "altitude": 1110,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "石会义",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·赵家圪道 榆树",
      "address": "山西省长治市上党区荫城镇横河村委会赵家圪道",
      "location": "赵家圪道",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400032",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "魁池",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.15,
      "lat": 35.964444,
      "ownership": "个人",
      "age": 320,
      "grade": "2",
      "height": 18,
      "chest": 290,
      "ground": null,
      "avgCrown": 12,
      "ewCrown": 12,
      "nsCrown": 12,
      "altitude": 1110,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "王福生",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-02",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·魁池 国槐",
      "address": "山西省长治市上党区荫城镇横河村委会魁池",
      "location": "魁池",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400033",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "赵家圪道牛家老院",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.147118,
      "lat": 35.960536,
      "ownership": "个人",
      "age": 500,
      "grade": "1",
      "height": 12,
      "chest": 350,
      "ground": null,
      "avgCrown": 14,
      "ewCrown": 15,
      "nsCrown": 13,
      "altitude": 1090,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "牛家",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·赵家圪道牛家老院 国槐",
      "address": "山西省长治市上党区荫城镇横河村委会赵家圪道牛家老院",
      "location": "赵家圪道牛家老院",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400034",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "玉皇观",
      "family": "豆科",
      "genus": "合欢属",
      "species": "山合欢",
      "scientificName": "Albizia kalkora (Roxb.)Prai",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.134722,
      "lat": 35.963056,
      "ownership": "集体",
      "age": 160,
      "grade": "3",
      "height": 13.5,
      "chest": 190,
      "ground": null,
      "avgCrown": 12.5,
      "ewCrown": 14,
      "nsCrown": 11,
      "altitude": 1050,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树池",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "护栏,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·玉皇观 山合欢",
      "address": "山西省长治市上党区荫城镇横河村委会玉皇观",
      "location": "玉皇观",
      "protection": "护栏,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400035",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "玉皇观",
      "family": "柿科",
      "genus": "柿属",
      "species": "君迁子",
      "scientificName": "Diospyros lotus L",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.139167,
      "lat": 35.963889,
      "ownership": "集体",
      "age": 105,
      "grade": "3",
      "height": 9,
      "chest": 89,
      "ground": null,
      "avgCrown": 7.5,
      "ewCrown": 7,
      "nsCrown": 8,
      "altitude": 1050,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "据村70岁老人回忆，孩童时期这树即有碗口粗，每年收获果实时修建枝桠，所以长不粗",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·玉皇观 君迁子",
      "address": "山西省长治市上党区荫城镇横河村委会玉皇观",
      "location": "玉皇观",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400036",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "玉皇观",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.1375,
      "lat": 35.963889,
      "ownership": "集体",
      "age": 120,
      "grade": "3",
      "height": 18,
      "chest": 71,
      "ground": null,
      "avgCrown": 2,
      "ewCrown": 2,
      "nsCrown": 2,
      "altitude": 1040,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "树木在房崖上生长，生存环境及其恶劣",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·玉皇观 侧柏",
      "address": "山西省长治市上党区荫城镇横河村委会玉皇观",
      "location": "玉皇观",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400037",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "玉皇观念",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.1375,
      "lat": 35.963889,
      "ownership": "集体",
      "age": 100,
      "grade": "3",
      "height": 15.5,
      "chest": 50,
      "ground": null,
      "avgCrown": 2,
      "ewCrown": 2,
      "nsCrown": 2,
      "altitude": 1040,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "树木在房崖上生长，环境及其恶劣",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·玉皇观念 侧柏",
      "address": "山西省长治市上党区荫城镇横河村委会玉皇观念",
      "location": "玉皇观念",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400038",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "旧庙院内",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.133333,
      "lat": 35.946944,
      "ownership": "集体",
      "age": 110,
      "grade": "3",
      "height": 10.5,
      "chest": 90,
      "ground": null,
      "avgCrown": 5,
      "ewCrown": 6,
      "nsCrown": 4,
      "altitude": 1020,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·旧庙院内 侧柏",
      "address": "山西省长治市上党区荫城镇横河村委会旧庙院内",
      "location": "旧庙院内",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400039",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "横河村委会",
      "place": "旧苗院内",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.133333,
      "lat": 35.946944,
      "ownership": "集体",
      "age": 110,
      "grade": "3",
      "height": 11.5,
      "chest": 89,
      "ground": null,
      "avgCrown": 4,
      "ewCrown": 4,
      "nsCrown": 4,
      "altitude": 1020,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·横河村委会·旧苗院内 侧柏",
      "address": "山西省长治市上党区荫城镇横河村委会旧苗院内",
      "location": "旧苗院内",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400040",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "长春村委会",
      "place": "大寨",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.118611,
      "lat": 35.966944,
      "ownership": "个人",
      "age": 1100,
      "grade": "1",
      "height": 20,
      "chest": 500,
      "ground": null,
      "avgCrown": 18,
      "ewCrown": 19,
      "nsCrown": 17,
      "altitude": 1020,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "郭天起",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-03",
      "archiveYear": "未标注",
      "name": "荫城镇·长春村委会·大寨 国槐",
      "address": "山西省长治市上党区荫城镇长春村委会大寨",
      "location": "大寨",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400041",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "信义村委会",
      "place": "槐树底下",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.076389,
      "lat": 36.144444,
      "ownership": "集体",
      "age": 150,
      "grade": "3",
      "height": 10.5,
      "chest": 270,
      "ground": null,
      "avgCrown": 11.5,
      "ewCrown": 10,
      "nsCrown": 13,
      "altitude": 950,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "信义",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "郝家庄镇·信义村委会·槐树底下 国槐",
      "address": "山西省长治市上党区郝家庄镇信义村委会槐树底下",
      "location": "槐树底下",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400042",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "郝家庄镇",
      "village": "寨子村委会",
      "place": "靳家老院",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.088889,
      "lat": 36.154722,
      "ownership": "个人",
      "age": 105,
      "grade": "3",
      "height": 17.5,
      "chest": 205,
      "ground": null,
      "avgCrown": 12,
      "ewCrown": 14,
      "nsCrown": 10,
      "altitude": 930,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "靳家",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "郝家庄镇·寨子村委会·靳家老院 国槐",
      "address": "山西省长治市上党区郝家庄镇寨子村委会靳家老院",
      "location": "靳家老院",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400043",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "中村村委会",
      "place": "冯安民院外",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.094444,
      "lat": 35.991667,
      "ownership": "个人",
      "age": 120,
      "grade": "3",
      "height": 19.5,
      "chest": 195,
      "ground": null,
      "avgCrown": 13.5,
      "ewCrown": 13,
      "nsCrown": 14,
      "altitude": 990,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "冯安民",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "荫城镇·中村村委会·冯安民院外 国槐",
      "address": "山西省长治市上党区荫城镇中村村委会冯安民院外",
      "location": "冯安民院外",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400044",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "河南村委会",
      "place": "未标注",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.084722,
      "lat": 35.986389,
      "ownership": "个人",
      "age": 515,
      "grade": "1",
      "height": 23,
      "chest": 350,
      "ground": null,
      "avgCrown": 22,
      "ewCrown": 21,
      "nsCrown": 23,
      "altitude": 1010,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "原晋丽",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "荫城镇·河南村委会 国槐",
      "address": "山西省长治市上党区荫城镇河南村委会未标注",
      "location": "未标注",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": "小地名缺失，地图弹窗可先用乡镇/村委会+树种展示"
    },
    {
      "id": "14040400045",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "河南村委会",
      "place": "秦青山院外",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.085,
      "lat": 35.986389,
      "ownership": "个人",
      "age": 100,
      "grade": "3",
      "height": 15.5,
      "chest": 185,
      "ground": null,
      "avgCrown": 11.5,
      "ewCrown": 10,
      "nsCrown": 13,
      "altitude": 1010,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "一主干缺损",
      "maintainerType": "未标注",
      "maintainer": "秦青山",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "荫城镇·河南村委会·秦青山院外 国槐",
      "address": "山西省长治市上党区荫城镇河南村委会秦青山院外",
      "location": "秦青山院外",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400046",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "峰上掌村委会",
      "place": "煤窑沟",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.133889,
      "lat": 35.989722,
      "ownership": "个人",
      "age": 350,
      "grade": "2",
      "height": 23.5,
      "chest": 350,
      "ground": null,
      "avgCrown": 15.5,
      "ewCrown": 18,
      "nsCrown": 13,
      "altitude": 1070,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "李治伟",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "荫城镇·峰上掌村委会·煤窑沟 国槐",
      "address": "山西省长治市上党区荫城镇峰上掌村委会煤窑沟",
      "location": "煤窑沟",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400047",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "荫城镇",
      "village": "郭良村委会",
      "place": "奶奶庙内",
      "family": "柏科",
      "genus": "侧柏属",
      "species": "侧柏",
      "scientificName": "Platycladus orientalis",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.135278,
      "lat": 35.97222,
      "ownership": "集体",
      "age": 122,
      "grade": "3",
      "height": 10.5,
      "chest": 105,
      "ground": null,
      "avgCrown": 6.5,
      "ewCrown": 7,
      "nsCrown": 6,
      "altitude": 0,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "郭良村",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-08-15",
      "archiveYear": "未标注",
      "name": "荫城镇·郭良村委会·奶奶庙内 侧柏",
      "address": "山西省长治市上党区荫城镇郭良村委会奶奶庙内",
      "location": "奶奶庙内",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400048",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "振兴新区",
      "village": "振兴村委会",
      "place": "槐荫寺外",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.120833,
      "lat": 35.8975,
      "ownership": "集体",
      "age": 750,
      "grade": "1",
      "height": 12,
      "chest": 430,
      "ground": null,
      "avgCrown": 16.5,
      "ewCrown": 17,
      "nsCrown": 16,
      "altitude": 1110,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：护栏,树洞封堵,树池",
      "maintainerType": "未标注",
      "maintainer": "振兴村委",
      "department": "未标注",
      "measure": "护栏,树洞封堵,树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "振兴新区·振兴村委会·槐荫寺外 国槐",
      "address": "山西省长治市上党区振兴新区振兴村委会槐荫寺外",
      "location": "槐荫寺外",
      "protection": "护栏,树洞封堵,树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400049",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "振兴新区",
      "village": "振兴村委会",
      "place": "花间堂",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.118611,
      "lat": 35.894722,
      "ownership": "集体",
      "age": 170,
      "grade": "3",
      "height": 12,
      "chest": 210,
      "ground": null,
      "avgCrown": 7.5,
      "ewCrown": 9,
      "nsCrown": 6,
      "altitude": 1110,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树池",
      "maintainerType": "未标注",
      "maintainer": "振兴村委",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "振兴新区·振兴村委会·花间堂 国槐",
      "address": "山西省长治市上党区振兴新区振兴村委会花间堂",
      "location": "花间堂",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400050",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "西火镇",
      "village": "西蛮掌村委会",
      "place": "旧村",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.134722,
      "lat": 35.9125,
      "ownership": "集体",
      "age": 540,
      "grade": "1",
      "height": 8,
      "chest": 360,
      "ground": null,
      "avgCrown": 10,
      "ewCrown": 10,
      "nsCrown": 10,
      "altitude": 1120,
      "soil": "未标注",
      "growth": "濒危",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "西蛮掌村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "西火镇·西蛮掌村委会·旧村 国槐",
      "address": "山西省长治市上党区西火镇西蛮掌村委会旧村",
      "location": "旧村",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400051",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "西火镇",
      "village": "平家庄村委会",
      "place": "牛街",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.137778,
      "lat": 35.924444,
      "ownership": "集体",
      "age": 990,
      "grade": "1",
      "height": 13.5,
      "chest": 500,
      "ground": null,
      "avgCrown": 13.5,
      "ewCrown": 14,
      "nsCrown": 13,
      "altitude": 1090,
      "soil": "未标注",
      "growth": "衰弱",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "平家庄村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "西火镇·平家庄村委会·牛街 国槐",
      "address": "山西省长治市上党区西火镇平家庄村委会牛街",
      "location": "牛街",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400052",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "西火镇",
      "village": "南河村委会",
      "place": "东头",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.178333,
      "lat": 35.9275,
      "ownership": "集体",
      "age": 320,
      "grade": "2",
      "height": 16,
      "chest": 290,
      "ground": null,
      "avgCrown": 18.5,
      "ewCrown": 18,
      "nsCrown": 19,
      "altitude": 1090,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "已记录保护措施：树池",
      "maintainerType": "未标注",
      "maintainer": "井东村委",
      "department": "未标注",
      "measure": "树池",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "西火镇·南河村委会·东头 国槐",
      "address": "山西省长治市上党区西火镇南河村委会东头",
      "location": "东头",
      "protection": "树池",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400053",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "西火镇",
      "village": "南河村委会",
      "place": "后山",
      "family": "松科",
      "genus": "松属",
      "species": "油松",
      "scientificName": "Pinus tabuliformis Carriere",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.178333,
      "lat": 35.9275,
      "ownership": "集体",
      "age": 260,
      "grade": "3",
      "height": 11.5,
      "chest": 200,
      "ground": null,
      "avgCrown": 10.5,
      "ewCrown": 7,
      "nsCrown": 14,
      "altitude": 1117,
      "soil": "未标注",
      "growth": "正常",
      "environment": "好",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "井东村委",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "西火镇·南河村委会·后山 油松",
      "address": "山西省长治市上党区西火镇南河村委会后山",
      "location": "后山",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    },
    {
      "id": "14040400054",
      "category": "古树",
      "province": "山西省",
      "city": "长治市",
      "district": "上党区",
      "town": "西火镇",
      "village": "北大掌村委会",
      "place": "里家后",
      "family": "豆科",
      "genus": "槐属",
      "species": "国槐",
      "scientificName": "Sophora japonica L.",
      "commonName": "",
      "growthPlace": "乡村",
      "distribution": "散生",
      "lng": 113.184722,
      "lat": 35.915556,
      "ownership": "个人",
      "age": 240,
      "grade": "3",
      "height": 24,
      "chest": 24,
      "ground": null,
      "avgCrown": 19,
      "ewCrown": 19,
      "nsCrown": 19,
      "altitude": 1120,
      "soil": "未标注",
      "growth": "正常",
      "environment": "差",
      "damage": "暂无明显损伤记录",
      "story": "现有数据表暂未记录故事材料，后续实地调研补充照片、访谈与保护信息。",
      "maintainerType": "未标注",
      "maintainer": "张恒文",
      "department": "未标注",
      "measure": "待补充",
      "revive": "待补充",
      "surveyPerson": "王思远",
      "surveyDate": "2017-09-15",
      "archiveYear": "未标注",
      "name": "西火镇·北大掌村委会·里家后 国槐",
      "address": "山西省长治市上党区西火镇北大掌村委会里家后",
      "location": "里家后",
      "protection": "待补充",
      "coordinate_status": "正常",
      "data_note": ""
    }
  ]
};
